title: Dani Massarano
subtitle: Data Engineer, Hacker, Caffeine Enthusiast
description: >-
  I'm a data engineer and I'm interested in big data, security, and automation

image:
  path: android-chrome-512x512
  height: 100
  width: 100
url: "https://danmassarano.com"
baseurl: ""

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    # - text: Blog
    #   url: /blog
    # - text: Contact
    #   url : /contact


# Edit Author details (For multi authors check _data/authors.yml)
author_logo: avatar_small.png
author_logo_webp: avatar_small.webp
author: Dani
author_bio:
    Data Engineer by day, wannabe hacker by night. I like learning new things and either making or breaking stuff is my favourite way to do it.
author_email: "dmassarano@outlook.com"
author_location: Manchester, UK
author_website_url: "danmassarano.com"
typewrite-text:
    I'm a data engineer and I'm interested in big data, security, and automation
hero_cover_img: banner.png
hero_cover_img_webp: banner.webp

# Experiences
author_work_experiences:
            - company_name: Hippo
              company_logo: career/hippo_digital.png
              company_logo_webp: career/hippo_digital.webp
              company_url: https://hippodigital.co.uk/
              designation: Senior Data Engineer
              description: Tech lead for a team working on projects in GCP to design, build, test, and deliver data platforms.
              visibility: true
            - company_name: The Data Shed
              company_logo: career/the_data_shed.png
              company_logo_webp: career/the_data_shed.webp
              company_url: https://thedatashed.co.uk/
              designation: Senior Data Engineer
              description: Tech lead for a team working on projects in GCP to design, build, test, and deliver data platforms.
              visibility: true
            - company_name: KPMG UK
              company_logo: career/kpmg.jpg
              company_logo_webp: career/kpmg.webp
              company_url: https://home.kpmg/uk/en/home.html
              designation: Data Engineer
              description: Developed data solutions to automate business processes and aid reporting for business-critical applications. Designed data architecture and created ETL pipelines in ADF and SSIS.
              visibility: true

# Projects
author_project_details:
              - project_thumbnail: projects/try_hack_me.png
                project_thumbnail_webp: projects/try_hack_me.webp
                project_title: TryHackMe
                project_info: Cyber Security Training
                project_description: A great platform to learn about security with tutorials, labs and CTF's. I'm learning a load about pentesting, exploitation, red/blue teaming, secure coding and more.
                # project_url: https://tryhackme.com/p/purpl3d0ll
                custom_input: <script src="https://tryhackme.com/badge/1536845"></script>
                visibility: true

# Education
author_education_details:
              - college_logo: career/university_of_manchester.jpg
                college_logo_webp: career/university_of_manchester.webp
                college_name: The University of Manchester
                college_url: https://www.manchester.ac.uk/
                college_degree: Computer Science
                description: BSc (Hons)
                visibility: true

# Certifications
author_certification_details:
              - organisation_logo: certs/gcp-professional-data-engineer.png
                organisation_logo_webp: certs/gcp-professional-data-engineer.webp
                issuing_org: Google
                cartification_name: Google Cloud Certified Professional Data Engineer
                issue_date: Aug 2023
                verify_url: https://google.accredible.com/027190fe-8bc0-4c02-a884-18e275a7a168
                visibility: true
              - organisation_logo: certs/gcp_cloud_engineer.png
                organisation_logo_webp: certs/gcp_cloud_engineer.webp
                issuing_org: Google
                cartification_name: Google Cloud Certified Associate Cloud Engineer
                issue_date: Jul 2022
                verify_url: https://google.accredible.com/18ce7dc0-a7dc-4707-8733-d71053b46d02
                visibility: true
              - organisation_logo: certs/gcp_cloud_digital_leader.png
                organisation_logo_webp: certs/gcp_cloud_digital_leader.webp
                issuing_org: Google
                cartification_name: Google Cloud Certified Cloud Digital Leader
                issue_date: Nov 2021
                verify_url: https://www.credential.net/2d924198-4dbe-4be9-b2c1-1cce51a267ec
                visibility: true
              - organisation_logo: certs/azure_data_engineer_associate.png
                organisation_logo_webp: certs/azure_data_engineer_associate.webp
                issuing_org: Microsoft
                cartification_name: "Microsoft Certified: Azure Data Engineer Associate"
                issue_date: Dec 2020
                verify_url: https://www.youracclaim.com/badges/63ba3ba5-a0d4-4964-8e3d-1e592904d1be
                visibility: true
              - organisation_logo: certs/azure_data_fundamentals.png
                organisation_logo_webp: certs/azure_data_fundamentals.webp
                issuing_org: Microsoft
                cartification_name: "Microsoft Certified: Azure Data Fundamentals"
                issue_date: Aug 2020
                verify_url: https://www.youracclaim.com/badges/1410afa3-c7f8-4433-bbe5-73b5778a8eaa
                visibility: true
              - organisation_logo: certs/azure_fundamentals.png
                organisation_logo_webp: certs/azure_fundamentals.webp
                issuing_org: Microsoft
                cartification_name: "Microsoft Certified: Azure Fundamentals"
                issue_date: Mar 2020
                verify_url: https://www.youracclaim.com/badges/739dc1e5-8711-4f72-a95e-404614f301f0
                visibility: true
              - organisation_logo: certs/aws_certified_cloud_practitioner.png
                organisation_logo_webp: certs/aws_certified_cloud_practitioner.webp
                issuing_org: Amazon Web Services (AWS)
                cartification_name: AWS Certified Cloud Practitioner
                issue_date: Dec 2019
                verify_url: https://www.youracclaim.com/badges/03d1308f-da29-4b78-8107-280993eeb5b4
                visibility: true
              - organisation_logo: certs/databricks_lakehouse_fundamentals.png
                organisation_logo_webp: certs/databricks_lakehouse_fundamentals.webp
                issuing_org: Databricks
                cartification_name: "Databricks Lakehouse Fundamentals"
                issue_date: Dec 2023
                verify_url: https://credentials.databricks.com/88d2da48-ac34-40d8-a157-9bd36468cee3#gs.1p547y
                visibility: true
              - organisation_logo: certs/hashicorp-certified-terraform-associate-003.png
                organisation_logo_webp: certs/hashicorp-certified-terraform-associate-003.webp
                issuing_org: HashiCorp
                cartification_name: "HashiCorp Certified: Terraform Associate"
                issue_date: Feb 2024
                verify_url: https://www.credly.com/badges/1695833c-e63d-447c-8c94-5071ff348bef
                visibility: true
              - organisation_logo: certs/professional_scrum_master_i_psm_i.png
                organisation_logo_webp: certs/professional_scrum_master_i_psm_i.webp
                issuing_org: Scrum.org
                cartification_name: Professional Scrum Masterâ„¢ I (PSM I)
                issue_date: Jul 2021
                verify_url: https://www.credly.com/badges/0fb65c51-8ff5-4b61-94ed-0837dab8cd9b
                visibility: true
              - organisation_logo: certs/itil_foundation.png
                organisation_logo_webp: certs/itil_foundation.webp
                issuing_org: AXELOS Global Best Practice
                cartification_name: ITIL Foundation
                issue_date: Dec 2018
                verify_url: https://www.youracclaim.com/badges/d3c5348a-989e-4e36-b9ea-93795b3bf2a6
                visibility: true

# social links
github_username:  danmassarano
linkedin_username: dmassarano

# mailchimp embedded form url (newsletter):
# mailchimp_form_url:

# contact form - (choose formspress or getform)
# getform_endpoint:
# formspree_email:

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show
show_author_work_experiences: true
show_author_project_details: true
show_author_education_details: true
show_author_certification_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
